catalog:
  "@antfu/ni": ^28.0.0
  "@types/node": ^22.19.1
  "@xiaohe01/eslint-config": ^4.0.0
  "@xiaohe01/tsconfig": ^3.0.0
  eslint: ^9.39.1
  esno: ^4.8.0
  lint-staged: ^16.2.7
  simple-git-hooks: ^2.13.1
  typescript: ~5.9.3
  vite: ^7.2.6
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks